### ISSUE TITLE
nene212010@gmail.com

### ISSUE THREAD

**Issue by Fernando2018s** [jcfr/ResEdit#10]
_comment removed by @jcfr as it pointed to some arbitrary release asset without any context_

**Comment by Fernando2018s** [comment]
> https://objects.githubusercontent.com/github-production-release-asset-2e65be/1840080/1ab4777a-2685-11e7-9bb8-890b5954a91b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240706%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240706T065451Z&X-Amz-Expires=300&X-Amz-Signature=8a3033278cd2795a8c800df733ac329f6e1c6fe5549fa8cca1eb91310188d545&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=1840080&response-content-disposition=attachment%3B%20filename%3DCTKResEdit-0.1.0-g53f7-win-i386.tar.gz&response-content-type=application%2Foctet-stream

**Comment by jcfr** [comment]
@Fernando2018s To avoid misleading users and developers, I will remove this issue and associated comment.
