### ISSUE TITLE
Does this tool support editing resources in Android executable ?

### ISSUE THREAD

**Issue by Fernando2018s** [jcfr/ResEdit#8]
- A un miembro de la familia le gustaría que te unieras a la aplicación Microsoft Family Safety. Obtén la aplicación Microsoft Family Safety y comienza a crear hábitos digitales saludables con tu familia. 
https://aka.ms/FamilysafetyonAndroid[]()

**Comment by jcfr** [comment]
Similarly to the answer provided in the context of https://github.com/jcfr/ResEdit/issues/9, this tool does not support Android executable.

**Comment by Fernando2018s** [comment]
[]()
